from github import Github, GithubException
import os
from dotenv import load_dotenv
import datetime
import re

load_dotenv()

class GitHubManager:
    """
    Manages GitHub repository operations
    Future-proof: Can use user's token or default token
    """
    
    def __init__(self, token=None):
        """
        Initialize GitHub manager
        token: Optional user's GitHub token. If None, uses default from .env
        """
        self.token = token or os.getenv('GITHUB_TOKEN')
        if not self.token:
            raise ValueError("No GitHub token provided")
        
        self.github = Github(self.token)
        self.user = self.github.get_user()
    
    def generate_repo_name(self, description):
        """
        Generate a unique, valid GitHub repository name from description
        """
        # Clean the description
        clean_desc = description.lower()
        # Remove special characters, keep only alphanumeric and spaces
        clean_desc = re.sub(r'[^a-z0-9\s]', '', clean_desc)
        # Take first 3-4 words
        words = clean_desc.split()[:3]
        base_name = '-'.join(words) if words else 'ai-website'
        
        # Add timestamp for uniqueness
        timestamp = datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
        repo_name = f"{base_name}-{timestamp}"
        
        # GitHub repo names must be <= 100 characters
        if len(repo_name) > 100:
            repo_name = repo_name[:100]
        
        return repo_name
    
    def create_repository(self, repo_name, description="AI Generated Website", private=False):
        """
        Create a new GitHub repository
        
        Args:
            repo_name: Name of the repository
            description: Repository description
            private: Whether repo should be private (default: False)
        
        Returns:
            GitHub repository object
        """
        try:
            print(f"Creating GitHub repository: {repo_name}")
            
            repo = self.user.create_repo(
                name=repo_name,
                description=description,
                private=private,
                auto_init=False  # We'll add files manually
            )
            
            print(f"✓ Repository created: {repo.html_url}")
            return repo
            
        except GithubException as e:
            if e.status == 422:
                # Repository already exists, try with different name
                new_name = f"{repo_name}-{datetime.datetime.now().strftime('%H%M%S')}"
                print(f"Repository exists, trying: {new_name}")
                return self.create_repository(new_name, description, private)
            else:
                raise Exception(f"Failed to create repository: {str(e)}")
    
    def push_files(self, repo, files):
        """
        Push multiple files to the repository
        
        Args:
            repo: GitHub repository object
            files: Dictionary of {filename: content}
        
        Returns:
            Repository URL
        """
        try:
            print(f"Pushing {len(files)} files to repository...")
            
            # Create README.md
            readme_content = f"""# AI Generated Website

This website was automatically generated using AI.

## Files
"""
            for filename in files.keys():
                readme_content += f"- {filename}\n"
            
            readme_content += f"""
## Generated
{datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## How to Use
1. Clone this repository
2. Open `index.html` in a browser (for vanilla projects)
3. Or run `npm install && npm start` (for React projects)

---
*Generated by AI Website Generator*
"""
            
            # Push README first
            repo.create_file(
                path="README.md",
                message="Initial commit: Add README",
                content=readme_content
            )
            print("✓ README.md created")
            
            # Push all generated files
            for filename, content in files.items():
                # Create subdirectories if needed
                path = filename
                
                repo.create_file(
                    path=path,
                    message=f"Add {filename}",
                    content=content
                )
                print(f"✓ {filename} pushed")
            
            print(f"✓ All files pushed successfully!")
            return repo.html_url
            
        except Exception as e:
            raise Exception(f"Failed to push files: {str(e)}")
    
    def create_and_push(self, description, files):
        """
        Complete workflow: Create repo and push files
        
        Args:
            description: Project description (for repo name and description)
            files: Dictionary of {filename: content}
        
        Returns:
            Dictionary with repo_name, repo_url, and success status
        """
        try:
            # Generate unique repo name
            repo_name = self.generate_repo_name(description)
            
            # Create repository
            repo = self.create_repository(
                repo_name=repo_name,
                description=f"AI Generated: {description}"
            )
            
            # Push files
            repo_url = self.push_files(repo, files)
            
            return {
                'success': True,
                'repo_name': repo_name,
                'repo_url': repo_url,
                'username': self.user.login
            }
            
        except Exception as e:
            return {
                'success': False,
                'error': str(e)
            }